baseURL = "https://locksmith-bushes-55518.netlify.com/"
languageCode = "en-us"
title = "My Hugo site"
theme = "ananke"

MetaDataFormat = "yaml"
Paginate = 3
SectionPagesmenu ="main"


[params]
twitter="https://www.twitter.com/t4ostra"